name: Run IR Bot

on:
  schedule:
    - cron: "0 6 * * *"   # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4

      - run: pip install requests pandas

      - run: python main.py
